#include <h3mparser/parseh3m.h>
#include <h3mparser/writeText.h>
#include <h3mparser/writeh3m.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>

namespace fs = std::filesystem;

namespace
{
  h3m::PlayerSpecs generateTestPlayerSpecs()
  {
    return h3m::PlayerSpecs{
      .can_be_human = false,
      .can_be_computer = false,
      .behavior = h3m::PlayerBehavior::Random,
      .customized_alignments = false,
      .allowed_alignments = h3m::AllowedAlignments{
        h3m::BitSet<2>({0xFF, 0x01})
      },
      .random_town = true,
      .main_town {},
      .starting_hero {
        .is_random = false,
        .type = static_cast<h3m::HeroType>(0xFF),
        .face = 0xFF
      },
      .additional_info {}
    };
  }

  h3m::Map generateTestMap()
  {
    constexpr std::uint32_t kMapSize = 36;

    return h3m::Map {
      .format = h3m::MapFormat::ShadowOfDeath,
      .basic_info {
        .is_playable = false,
        .map_size = kMapSize,
        .has_two_levels = false,
        .name = "Test map",
        .description = "Test map generated by h3mparser.",
        .difficulty = h3m::MapDifficulty::Easy,
        .max_hero_level = 0
      },
      .players {
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs()
      },
      .additional_info {
        // Normal victory condition.
        .victory_condition {},
        // Normal loss condition.
        .loss_condition {},
        // No teams.
        .teams {},
        // Disable all heroes.
        .heroes_availability {},
        // No placeholder heroes.
        .placeholder_heroes {},
        // No custom heroes.
        .custom_heroes {},
        .reserved {},
        .artifacts_nonavailability {},
        .spells_nonavailability {},
        .skills_nonavailability {},
        .rumors {
          h3m::Rumor {
            .name = "Rumor",
            .description = "This is the only rumor."
          }
        },
        // No heroes with customized settings.
        .heroes_settings {}
      },
      .tiles = std::vector<h3m::Tile>(kMapSize * kMapSize),
      .global_events {
        h3m::GlobalEvent {
          .name = "Global event",
          .message = "Enjoy some resources.",
          .resources {10, 5, 10, 5, 5, 5, 1000},
          .affected_players = h3m::BitSet<1>(std::array<std::uint8_t, 1> {0xFF}),
          .applies_to_human = true,
          .applies_to_computer = true,
          .day_of_first_occurence = 0,
          .repeat_after_days = 0
        }
      }
    };
  }
}

int main(int argc, char** argv)
{
  if (argc != 2) {
    std::cout << "Usage: h3mparser map-path" << std::endl;
    return -1;
  }

  try
  {
    const fs::path path_map(argv[1]);
    std::ifstream stream(path_map, std::ios_base::in | std::ios_base::binary);
    const h3m::Map map = h3m::parseh3m(stream);
    stream.close();
    h3m::writeText(std::cout, map);
    std::ofstream out_stream("no_objects_or_events.h3m", std::ios_base::out | std::ios_base::binary);
    h3m::writeh3m(out_stream, map);

    //{
    //  const fs::path test_map_path("test_map.h3m");
    //  std::ofstream out_stream(test_map_path, std::ios_base::out | std::ios_base::binary);
    //  const h3m::Map test_map = generateTestMap();
    //  std::cout << "Generated a test map." << std::endl;
    //  h3m::writeh3m(out_stream, test_map);
    //  std::cout << "Wrote the generated map to test_map.h3m." << std::endl;
    //}
  }
  catch (const std::exception& error)
  {
    std::cerr << error.what() << std::endl;
  }
  catch (...)
  {
    std::cerr << "Unknown error." << std::endl;
  }

  return 0;
}
