#include <h3mtxt/Fun/fakeIslands.h>
#include <h3mtxt/Fun/fillWithWaterTiles.h>
#include <h3mtxt/Fun/Util.h>
#include <h3mtxt/H3MWriter/writeh3m.h>
#include <h3mtxt/Map/Map.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <stdexcept>

namespace fs = std::filesystem;

using h3m::drawFakeDiagonalLandStripSE;
using h3m::drawFakeIsland;
using h3m::drawFakeMiniIsland;
using h3m::drawFakeVerticalLandStrip;
using h3m::fillWithWaterTiles;
using h3m::safeGetTile;

namespace
{
  h3m::PlayerSpecs generateTestPlayerSpecs()
  {
    return h3m::PlayerSpecs{
      .can_be_human = false,
      .can_be_computer = false,
      .behavior = h3m::PlayerBehavior::Random,
      .customized_alignments = false,
      .allowed_alignments {},
      .random_town = false,
      .main_town {},
      .starting_hero {
        .is_random = false,
        .type = static_cast<h3m::HeroType>(0xFF),
        .portrait = h3m::HeroPortrait::DEFAULT
      },
      .additional_info {}
    };
  }

  h3m::Map generateTestMap(std::uint32_t map_size = 36)
  {
    h3m::Map map {
      .format = h3m::MapFormat::ShadowOfDeath,
      .basic_info {
        .is_playable = false,
        .map_size = map_size,
        .has_two_levels = false,
        .name = "Test map",
        .description = "Test map generated by h3mparser.",
        .difficulty = h3m::MapDifficulty::Easy,
        .max_hero_level = 0
      },
      .players {
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs(),
        generateTestPlayerSpecs()
      },
      .additional_info {
        // Normal victory condition.
        .victory_condition {},
        // Normal loss condition.
        .loss_condition {},
        // No teams.
        .teams {},
        // Enable all heroes.
        .heroes_availability = h3m::HeroesAvailability::makeAllAvailability(),
        // No placeholder heroes.
        .placeholder_heroes {},
        // No custom heroes.
        .custom_heroes {},
        .reserved {},
        .artifacts_nonavailability {},
        .disabled_spells {},
        .disabled_skills {},
        .rumors {
          h3m::Rumor {
            .name = "Rumor",
            .description = "This is the only rumor."
          }
        },
        // No heroes with customized settings.
        .heroes_settings {}
      },
      .tiles = std::vector<h3m::Tile>(map_size * map_size, h3m::Tile{
        .terrain_type = h3m::TerrainType::Rock,
        .terrain_sprite = 0
      }),
      .global_events {
        h3m::GlobalEvent {
          h3m::TimedEventBase {
            .name = "Global event",
            .message = "Enjoy some resources.",
            .resources {
              .data {10, 5, 10, 5, 5, 5, 10000}
             },
            .affected_players {
              .bitset = 0xFF
            },
            .applies_to_human = true,
            .applies_to_computer = true,
            .day_of_first_occurence = 0,
            .repeat_after_days = 0
          }
        }
      }
    };
    return map;
  }

  constexpr bool isEligibleLavaTile(const h3m::Tile& tile) noexcept
  {
    // Lava sprites [49; 72] are "pure", i.e. they don't border other terrain types.
    return tile.terrain_type == h3m::TerrainType::Lava &&
           tile.terrain_sprite >= 49 &&
           tile.terrain_sprite <= 72;
  }

  // Replaces the sprites of "pure" Lava tiles with random animated Lava sprites.
  void makeUltimateLava(h3m::Map& map)
  {
    std::random_device rd;
    std::mt19937 gen(rd());
    // Sprites [65; 70] look like animated Lava tiles.
    std::uniform_int_distribution<> distrib_sprite(65, 70);
    std::uniform_int_distribution<> distrib_mirror(0, 3);
    for (h3m::Tile& tile : map.tiles)
    {
      if (isEligibleLavaTile(tile))
      {
        tile.terrain_sprite = distrib_sprite(gen);
        tile.mirroring = distrib_mirror(gen);
      }
    }
  }

  void drawFakeIslands(h3m::Map& map)
  {
    drawFakeIsland(map, 5, 5);
    drawFakeIsland(map, 5, 9);
    drawFakeIsland(map, 9, 5);
    drawFakeIsland(map, 9, 9);
    drawFakeMiniIsland(map, 20, 8);
    drawFakeMiniIsland(map, 20, 10);
    drawFakeMiniIsland(map, 22, 9);
    drawFakeMiniIsland(map, 24, 11);
    drawFakeMiniIsland(map, 22, 12);
    drawFakeMiniIsland(map, 25, 9);
    drawFakeMiniIsland(map, 26, 13);
    drawFakeVerticalLandStrip(map, 10, 15, 10);
    drawFakeVerticalLandStrip(map, 12, 15, 10);
    drawFakeVerticalLandStrip(map, 14, 15, 10);
    drawFakeDiagonalLandStripSE(map, 20, 20, 10);
    drawFakeDiagonalLandStripSE(map, 24, 20, 10);
  }

  h3m::Map generateMapWithAllTerrainSprites()
  {
    constexpr std::uint8_t kNumTerrainTypes = 10;

    h3m::Map map = generateTestMap(108);
    map.basic_info.name = "All terrain sprites";
    map.basic_info.description = "This map is a cheatsheet for viewing terrain sprites in H3M.\n"
                                 "Each tile (X, Y) has the terrain type X and the terrain sprite Y.\n"
                                 "If X is not a valid terrain type or Y is not a valid sprite for X, "
                                 "the tile has a campfire object on that tile.";
    for (h3m::Tile& tile : map.tiles)
    {
      tile.terrain_type = h3m::TerrainType::Rock;
      tile.terrain_sprite = 0;
    }
    for (std::uint8_t terrain_type_idx = 0; terrain_type_idx < kNumTerrainTypes; ++terrain_type_idx)
    {
      const h3m::TerrainType terrain_type = static_cast<h3m::TerrainType>(terrain_type_idx);
      const std::uint8_t num_sprites = h3m::countSprites(terrain_type);
      for (std::uint8_t sprite = 0; sprite < num_sprites; ++sprite)
      {
        if (h3m::Tile* tile = safeGetTile(map, sprite, terrain_type_idx))
        {
          tile->terrain_type = terrain_type;
          tile->terrain_sprite = sprite;
        }
      }
    }
    map.objects_attributes.push_back(h3m::ObjectAttributes{
      .def = "adcfra.def",
      .object_class = h3m::ObjectClass::CAMPFIRE,
      .object_number = 0,
      .object_group = h3m::ObjectGroup::Treasure,
      });
    for (std::uint32_t y = 0; y < map.basic_info.map_size; ++y)
    {
      const std::uint8_t num_sprites =
        (y >= kNumTerrainTypes) ? 0 : h3m::countSprites(static_cast<h3m::TerrainType>(y));
      for (std::uint32_t x = num_sprites; x < map.basic_info.map_size; ++x)
      {
        map.objects_details.push_back(h3m::ObjectDetails{
          .x = static_cast<std::uint8_t>(x),
          .y = static_cast<std::uint8_t>(y),
          .z = 0,
          .kind = 0
          });
      }
    }
    return map;
  }

  h3m::ObjectAttributes makeObjectAttributesSpellScroll()
  {
    return h3m::ObjectAttributes{
      .def = "AVA0001.def",
      .passability {255, 255, 255, 255, 255, 127},
      .actionability {0, 0, 0, 0, 0, 128},
      .allowed_landscapes = 511,
      .landscape_group = 1,
      .object_class = h3m::ObjectClass::SPELL_SCROLL,
      .object_number = 0,
      .object_group = h3m::ObjectGroup::Artifact,
      .is_ground = 0
    };
  }

  h3m::Map generateMapWithHeroes()
  {
    h3m::Map map = generateTestMap(36);
    map.basic_info.name = "Test spell scroll";
    map.basic_info.description = "Testing if a spell scroll can be added as an artifact.";
    for (h3m::Tile& tile : map.tiles)
    {
      tile.terrain_type = h3m::TerrainType::Grass;
      tile.terrain_sprite = 49;
    }
    constexpr std::uint32_t kHeroKind = 0;
    constexpr std::uint32_t kSpellScrollKind = 1;
    // Add heroes.
    map.objects_attributes.push_back(h3m::ObjectAttributes{
      .def = "ah00_e.def",
      .passability {255, 255, 255, 255, 255, 191},
      .actionability {0, 0, 0, 0, 0, 64},
      .object_class = h3m::ObjectClass::HERO,
      .object_number = 0,
      .object_group = h3m::ObjectGroup::Hero,
      .is_ground = 0
      });
    map.objects_details.push_back(h3m::ObjectDetails{
      .x = 1,
      .y = 0,
      .z = 0,
      .kind = kHeroKind,
      .details = h3m::ObjectDetailsData<h3m::MetaObjectType::HERO> {
        .absod_id = 69,
        .owner = 0,
        .type = h3m::HeroType::H3M_HERO_ORRIN,
        .secondary_skills = std::vector<h3m::SecondarySkill> {
          h3m::SecondarySkill {.type = h3m::SecondarySkillType::Estates, .level = 0xFF},
        },
        .patrol_radius = 255
      }
    });
    map.objects_details.push_back(h3m::ObjectDetails{
      .x = 10,
      .y = 10,
      .z = 0,
      .kind = kHeroKind,
      .details = h3m::ObjectDetailsData<h3m::MetaObjectType::HERO> {
        .absod_id = 666,
        .owner = 1,
        .type = h3m::HeroType::H3M_HERO_XERON,
        .patrol_radius = 255
      }
    });
    // Add a spell scroll.
    map.objects_attributes.push_back(makeObjectAttributesSpellScroll());
    map.objects_details.push_back(h3m::ObjectDetails{
      .x = 2,
      .y = 2,
      .z = 0,
      .kind = kSpellScrollKind,
      .details = h3m::ObjectDetailsData<h3m::MetaObjectType::SPELL_SCROLL> {
        .spell = h3m::SpellType::SLOW
      }
    });
    return map;
  }
}

int main(int argc, char** argv)
{
  if (argc != 2) {
    std::cout << "Usage: Fun map-path" << std::endl;
    return -1;
  }

  try
  {
    const fs::path path_map(argv[1]);
    std::ofstream out_stream(path_map, std::ios_base::out | std::ios_base::binary);
    //const h3m::Map map = generateMapWithHeroes();
    h3m::Map map = generateTestMap();
    fillWithWaterTiles(map);
    drawFakeIslands(map);
    h3m::writeh3m(out_stream, map);
  }
  catch (const std::exception& error)
  {
    std::cerr << error.what() << std::endl;
  }
  catch (...)
  {
    std::cerr << "Unknown error." << std::endl;
  }

  return 0;
}
